apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
    tier: db 
    project: roboshop
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db 
      project: roboshop
      # app: nginx-stateful # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: db 
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: chinna9967/mysql:1.0.0
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # this is PVC directly.
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None #headless
  selector:
    app: mysql
    tier: db 
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # this port belongs to service
    targetPort: 3306 # this port belongs to container